# Generated by Django 3.0.5 on 2020-05-08 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20200508_2350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersArticles',
        ),
    ]
